name       : perl-mime-charset
version    : 1.013.1
release    : 9
source     :
    - https://cpan.metacpan.org/authors/id/N/NE/NEZUMI/MIME-Charset-1.013.1.tar.gz : 1bb7a6e0c0d251f23d6e60bf84c9adefc5b74eec58475bfee4d39107e60870f0
homepage   : https://metacpan.org/pod/MIME::Charset
license    : GPL-2.0-or-later
component  : programming.perl
summary    : MIME::Charset - Charset Information for MIME
description: |
    MIME::Charset provides information about character sets used for MIME messages on Internet.
builddeps  :
    - perl-test-pod
    - perl-encode-eucjpascii
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
