name       : perl-mime-charset
version    : 1.012.2
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/N/NE/NEZUMI/MIME-Charset-1.012.2.tar.gz : 878c779c0256c591666bd06c0cde4c0d7820eeeb98fd1183082aee9a1e7b1d13
license    : GPL-2.0
component  : programming.perl
summary    : MIME::Charset - Charset Information for MIME
description: |
    MIME::Charset - Charset Information for MIME
builddeps  :
    - perl-test-pod
    - perl-encode-eucjpascii
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
