name       : perl-mime-charset
version    : 1.012
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/N/NE/NEZUMI/MIME-Charset-1.012.tar.gz : cee5d1d4184ad46ca17d995335bc8d9b6d95e1e64584079d032cf5f0c82dcccd
license    : GPL-2.0
component  : programming.perl
summary    : MIME::Charset - Charset Information for MIME
description: |
    MIME::Charset - Charset Information for MIME
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
